//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LTMS.Languages {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LTMS.Languages.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to បញ្ចូលថ្មី.
        /// </summary>
        public static string AddNew {
            get {
                return ResourceManager.GetString("AddNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ឈ្មោះពិត.
        /// </summary>
        public static string AgencyName {
            get {
                return ResourceManager.GetString("AgencyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ឈ្មោះហៅ.
        /// </summary>
        public static string AgencyNickname {
            get {
                return ResourceManager.GetString("AgencyNickname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ទិន្ន័យ.
        /// </summary>
        public static string Data {
            get {
                return ResourceManager.GetString("Data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ភេទ.
        /// </summary>
        public static string Gender {
            get {
                return ResourceManager.GetString("Gender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ម៉ឺនុយ.
        /// </summary>
        public static string MAINNAVIGATION {
            get {
                return ResourceManager.GetString("MAINNAVIGATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to នៃ.
        /// </summary>
        public static string Of {
            get {
                return ResourceManager.GetString("Of", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ទំព័រ.
        /// </summary>
        public static string Page {
            get {
                return ResourceManager.GetString("Page", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to លេខទូរស័ព្ទ.
        /// </summary>
        public static string PhoneNumber {
            get {
                return ResourceManager.GetString("PhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to សូមពិនិត្យឡើងវិញ.
        /// </summary>
        public static string PleaseCheckAgain {
            get {
                return ResourceManager.GetString("PleaseCheckAgain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to មានរួចហើយ.
        /// </summary>
        public static string ReadyExisted {
            get {
                return ResourceManager.GetString("ReadyExisted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ស្វែងរក.
        /// </summary>
        public static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ពេល.
        /// </summary>
        public static string ShiftDescription {
            get {
                return ResourceManager.GetString("ShiftDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ពេល.
        /// </summary>
        public static string ShiftDescriptionKh {
            get {
                return ResourceManager.GetString("ShiftDescriptionKh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ការបញ្ចូលមិនត្រឹមត្រូវ.
        /// </summary>
        public static string WrongEntry {
            get {
                return ResourceManager.GetString("WrongEntry", resourceCulture);
            }
        }
    }
}
